dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/754eed67f5ed5a0c5de5
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
  - coveralls
install: mvn package -Dgpg.skip=true
